### ISSUE TITLE
Showing dispersion formula in Main battery column.

### ISSUE THREAD

**Issue by AndrewTaro** [WoWs-Builder-Team/WoWs-ShipBuilder#10]
**Is your feature request related to a problem? Please describe.**
It is frustrating to open the graph and add a ship, then see the difference when comparing dispersions.

**Describe the solution you'd like**
I believe showing the dispersion formula in the Main battery column will solve the problem.

**Comment by floribe2000** [comment]
What part of the formula would you like to see exactly?
The whole formula or just some results?

**Comment by yesod30** [comment]
The results are already in the program, so i'm assuming the whole formula, i.e. R*10+22

**Comment by AndrewTaro** [comment]
> The results are already in the program, so i'm assuming the whole formula, i.e. R*10+22

Yes, I meant this sort of formula.
