### ISSUE TITLE
Wrong value for rudder shift time

### ISSUE THREAD

**Issue by Yuzorah** [WoWs-Builder-Team/WoWs-ShipBuilder#11]
The rudder shift value displayed is incorrect.

The thing is that in the gameparams.data, WG use some weird time unit specifically for the rudder shift time. Don't know the exact coefficient but it's roughly divided by 1.3 if you want to get close to the real in-game value in seconds.

**Comment by yesod30** [comment]
Seems the correct factor is 1/1.305

**Comment by EdibleBug** [comment]
Can confirm division factor by 1.305

**Comment by yesod30** [comment]
Fixed for the next release
