### ISSUE TITLE
Better handling of automation for data visualization

### ISSUE THREAD

**Issue by yesod30** [WoWs-Builder-Team/WoWs-ShipBuilder#125]
We need a better way to automate the stats visualization in the ship stats view. Currently we have a Dictionary, with the key being the stat name and the value being the value. This get automatically processed to add the measurement units and then shown through an ItemTemplate. This makes it impossible to have anything but a straight list of values, and any additional behaviour requires hardcoding.
The solution to use is to replace the Dictionary with a List of IDataContainer, that will have an implementation for each of the possible use cases. This way, we can use the DataTemplates to decalre one for each of the various subclasses, effectively automating the whole thing. To define the single properties behaviour we can use custom attributes, that will be read by the automation process, that will create the required IDataContainer objects and populate the list.

Steps:

- [ ] Create the interface IDataContainer
- [ ] Create the implementation for straight key value pair, tooltip and grouping/indentation
- [ ] Create the attributes for the previous implementations
- [ ] Update the automation method to return the List of IDataContainer
- [ ] Add the DataTemplates to the ShipStatsView

**Comment by floribe2000** [comment]
Possible solution:
```mermaid
classDiagram
class IDataElement {
    <<interface>>
}

class KeyValueDataElement {
    +string Key
    +string Value
}

class TooltipDataElement {
    +string Key
    +string Value
    +string Tooltip
}

class ValueDataElement {
    +string Value
}

class NestedDataElement {
    +string Key
    +IEnumerable~IDataElement~ Children
}

class KeyValueUnitDataElement {
    +string Key
    +decimal Value
    +string Unit
}

IDataElement <|-- KeyValueDataElement
IDataElement <|-- TooltipDataElement
IDataElement <|-- ValueDataElement
IDataElement <|-- NestedDataElement
IDataElement <|-- KeyValueUnitDataElement
```

Keys and unit keys always represent the localization key, actual localization is handled by the frontend.
