### ISSUE TITLE
[Bug] Splash radius of Depth charges are incorrect

### ISSUE THREAD

**Issue by AndrewTaro** [WoWs-Builder-Team/WoWs-ShipBuilder#128]
**Describe the bug**
The value shown in the ship-mounted depth charges is using "splashCubeSize * 30 / 2" but this parameter is irrelevant to the splash radius against submarines.

**To Reproduce**
1. Go to a ship
2. Check ASW Depth Charges
4. See an error

**Expected behavior**
The parameter should be "depthSplashRadius * 30" instead of the aforementioned value.

**Program version. You can find it in the Info tab of the setting window**
App Version: 1.4.5

**Data version. You can find it in the Info tab of the setting window**
Data Version: 0.11.3#2

**Comment by AndrewTaro** [comment]
Apparently, the ASW airstrike section shows the correct parameter while the ship-mounted DCs part is incorrect.

**Comment by yesod30** [comment]
Fixed through a DataConverter fix
