### ISSUE TITLE
[Bug] AA number of flaks remains unvaried when activating def AA with Aux. Armaments Mod. 2

### ISSUE THREAD

**Issue by QuantumQuacken** [WoWs-Builder-Team/WoWs-ShipBuilder#152]
**Describe the bug**
When equipping Aux. Armaments Mod. 2 and activating (right-click) the Def AA consumable, the number of flaks remains unvaried.

**To Reproduce**
1. Select a ship with Def. AA consumable and equip Aux. Armaments Mod. 2 in the 6th slot.
2. Right click on the Def. AA consumable.
3. See flak number staying the same.

**Expected behavior**
When right clicking def AA with Aux. Armaments Mod. 2, the number of flaks should increase like the damage does.

App Version: 1.5.3
Data Version: 0.11.6#1

**Comment by floribe2000** [comment]
Also affecting web
