### ISSUE TITLE
[Bug] Crash when selecting a carrier

### ISSUE THREAD

**Issue by dmc531** [WoWs-Builder-Team/WoWs-ShipBuilder#17]
**Describe the bug**
Shipbuilder crashes upon selection of any carrier with no error message.

**To Reproduce**
1. Go to 'Create new build'
2. Click on any carrier
3. Get a crash with no error message

**Expected behavior**
A build screen opening with the selected carrier.

**Screenshots**
No screenshots of it crashing sadly

**Program version - 1.0.4**

**Data version - 0.10.9#12**

**Comment by floribe2000** [comment]
The crash cannot be reproduced with the current gamedata version. Please try updating the gamedata version (should happen automatically). I think we had a bug in the version you use.
If it doesn't work, please send me the logfile.

**Comment by floribe2000** [comment]
Should no longer be possible in new releases
