### ISSUE TITLE
[Bug] Heavy HE skill does not increase concealment on large gunned ships

### ISSUE THREAD

**Issue by Fafniroth** [WoWs-Builder-Team/WoWs-ShipBuilder#19]
**Describe the bug**
Heavy HE and SAP Shells skill should increase concealment for ships with gun caliber above 149mm. It doesn't.

**To Reproduce**
1. Select a heavy cruiser (I used Saint-Louis).
2. Go to Captain Skills.
2. Select Heavy HE and SAP Shells.
3. Check the Concealment tab.
4. Values are unchanged.

**Expected behavior**
When selecting the skill on ships with gun caliber above 149mm, detectability should increase by 15%.

**Program version: 1.0.4**

**Data version: 0.10.10#3**

**Comment by yesod30** [comment]
Fixed for the next release
