### ISSUE TITLE
[Suggestion] Show the detailed info about the homing torpedoes

### ISSUE THREAD

**Issue by AndrewTaro** [WoWs-Builder-Team/WoWs-ShipBuilder#193]
**Describe the solution you'd like**
Please display the following parameters on the submarine torpedoes:
- The distance at which the guidance turns off (`dropTargetAtDistance`)
- Maximum turning speed and acceleration (`maxYaw` and `yawChangeSpeed`)
- Maximum vertical speed and acceleration (`maxVerticalSpeed` and `verticalAcceleration`)
- The radius and angle of which the torpedo search for the pinged vehicle (`searchAngle` and `searchRadius`)

**Comment by floribe2000** [comment]
Requires data converter update, will be implemented as soon as possible
