### ISSUE TITLE
[Bug] Consumable cooldown not affected by skills/signals - Web

### ISSUE THREAD

**Issue by QuantumQuacken** [WoWs-Builder-Team/WoWs-ShipBuilder#249]
**Describe the bug**
Including the _Consumable Specialist_ skill or the _November Foxtrot_ signal has no impact on the reload time of consumables in the web-based version. The desktop version could not be tested because of #248.

**Expected behavior**
I would expect to see the reload time for consumable items reduced after selecting any of the aforementioned options.

**Comment by iTTou** [comment]
Fixed in the next update
