### ISSUE TITLE
Rework ShipStats page

### ISSUE THREAD

**Issue by floribe2000** [WoWs-Builder-Team/WoWs-ShipBuilder#251]
- [x] - collapsed subsections by default
- [x] - move settings link to regular navigation
- [x] - move secondary range into main secondary expander
- [x] - Remove detection from subs at maximum depth from concealment data container
- [x] - swap positions of concealment and maneuverability datacontainer
- [x] - consider adding icon for shell type, alternatively: prefix shell name with shell type
- [x] - share expander state between tabs within one session (enabled by default, maybe optional)
- [x] - show "add new ship" when removing last ship on ships page (evaluate embedding selector in page vs. opening popup as usual)
- [x] - check if tabs header can be made sticky

**Comment by iTTou** [comment]
- add secondaries max range dispersion
