### ISSUE TITLE
Rework ShipComparison page

### ISSUE THREAD

**Issue by floribe2000** [WoWs-Builder-Team/WoWs-ShipBuilder#252]
- [x] - show unlimited ships per page (just add stupidly high number)
- [x] - hide rearrange icon and remove blocked space
- [x] - remove unnecessarily blocked space in column headers (especially the right padding)
- [ ] - Remove supership category, map to tech tree
- [x] - put all/none selectors at the front, alternatively try to align them using a table
- [x] - add tooltip to nation flags
- [ ] - use 50 rows per page by default
- [x] - remember user settings for comparison (firing range, hidden columns, rows per page, stock/top button, hide ships without section button)
- [x] - save pinned ships in URL, limit to 100, also limit in ShipStats

**Comment by iTTou** [comment]
Remove supership category and map to tech tree has to be done at data converter level. It will automatically update on the ship comparison.
It has been decided to entirely remove grid pagination.
