### ISSUE TITLE
Choose of ship modules dont work on mobile[Bug]

### ISSUE THREAD

**Issue by vge-lab** [WoWs-Builder-Team/WoWs-ShipBuilder#303]
**Describe the bug**
On mobile view in ship page, choose of ship modules dont work. On click + modules shows, and if I choose one then do nothing.
And no module is choosen.

**To Reproduce**
Open your app on mobile device. Or in PC browser with mobile view enabled.
1. Select any ship a go to ship building page
2. Click on + in module choose section
3. Choose any upgrade module
4. And nothing happens

**Expected behavior**
After choose one module, module ahiws as choosen and stat are recompute.

**Screenshots**
Dont have.

**(Desktop only) Program version. You can find it at the top of the settings window.**

**Data version. You can find it at the top of the settings window.**
0.13.1#1

**Server type (Live or PTS)**
Live

**Additional context**
Nothing.

**Comment by floribe2000** [comment]
Thank you for the report, it seems like this is an issue with the component library we are using. We will check if there is any workaround for this until the library has fixed the problem.
