### ISSUE TITLE
[Enhancement/Bug] Handle nation of components that have a different nation than the ship itself

### ISSUE THREAD

**Issue by floribe2000** [WoWs-Builder-Team/WoWs-ShipBuilder#31]
In some cases, there are ship components like artillery shells that have a different nation than the currently selected ship.
Due to the caching, this can result in exceptions.

Add a new check to parse the nation from the component index and use the correct data file to retrieve the data.

**Comment by yesod30** [comment]
As an additional point, we should also check if the cache is different from null. Some nations don't have, for example, an aircraft file, meaning it's never getting cached, possibly causing null references
