### ISSUE TITLE
[README Issue] Wrong link in "Translation help" section

### ISSUE THREAD

**Issue by heppocogne** [WoWs-Builder-Team/WoWs-ShipBuilder#314]
**Describe the bug**
Clicking "... you can find [here](https://github.com/WoWs-Builder-Team/WoWs-ShipBuilder/blob/main/.github/Translation%20guide.md#how-to-help-with-the-translation)." in **Translation help** section in README.md result in "404 - page not found".

**Expected behavior**
The correct link might be https://github.com/WoWs-Builder-Team/WoWs-ShipBuilder/blob/development/.github/CONTRIBUTING.md#helping-with-translating-the-project (?)

**Comment by floribe2000** [comment]
Thanks for the report, seems like we forgot to fix some stuff when we rearranged docs. I'll fix this asap.
