### ISSUE TITLE
[Bug] [Web app] An error has occurred. This application may no longer respond until reloaded.

### ISSUE THREAD

**Issue by YurraSickpark** [WoWs-Builder-Team/WoWs-ShipBuilder#315]
The application gives out the error message "An error has occurred. This application may no longer respond until reloaded." when trying to select an upgrades for the Fenyang for the live server version of the web app. This only appears to be an issue for the Fenyang in particular, I have tried a dozen other ships which seem to behave correctly.

1. Select Fenyang as your desired ship for a build.
2. Start selecting upgrades.
3. See error message at the bottom of the page.

![Image](https://github.com/user-attachments/assets/28a36ead-9048-41d8-809a-913fafdef3aa)

Current data version: 0.13.10#1, live server.

**Comment by floribe2000** [comment]
Thanks for the report. The issue should be fixed now.
