### ISSUE TITLE
[Bug] Dispersion graph doesn't take into account dispersion modifiers

### ISSUE THREAD

**Issue by yesod30** [WoWs-Builder-Team/WoWs-ShipBuilder#39]
**Describe the bug**
The dispersion graph doesn't seems to take into account installed modules for the currently selected ship

**Expected behavior**
The graph should take into account changes due to modules and/or skills for the currently selected ship only. It would also help in seeing the actual difference in effectiveness of modules

**Program version. You can find it in the Info tab of the setting window**
All
**Data version. You can find it in the Info tab of the setting window**
All

**Comment by floribe2000** [comment]
Working as intended, will be changed as part of #83
