### ISSUE TITLE
[Suggestion] Open multiple windows of ship stats

### ISSUE THREAD

**Issue by AndrewTaro** [WoWs-Builder-Team/WoWs-ShipBuilder#48]
**Is your feature request related to a problem? Please describe.**
There is a difficulty when comparing two or more ships because the ship stats are always in one window.

**Describe the solution you'd like**
+ Add an option to display ship statistics in a new window on the screen where you select a ship.
+ Or, add something like a tab.

**Comment by floribe2000** [comment]
Implemented in common UI, will be available for desktop with release 2.0.0
